### PR TITLE
Update publications and projects

### PR DESCRIPTION
**Pull request by acka47**
- Update gatsby starter c600a48cbaf4d19b346fa66b8737d6ff8f361503
- Add metadaten.community as product
- Add end date to projects: ORCA.nrw, Alma migration and AMB
- Add several missing presentation slides from 2023

To Do:
- [x] add end date for Metafacture Fix project
- [ ] add end date to Metafacture Playground project
- [ ] ~~Add several missing SkoHub blog posts (last one is from July 2021)~~

Re. the last point: @sroertgen it probably makes sense to open a separate issue for this and maybe even write a script to create the JSON files automatically?

### CODE REVIEW

**Comment by acka47** [comment]
I marked this as draft because the metadaten.community product page is not built locally. @fsteeg please take a look as I can not figure it out by myself.

**Comment by acka47** [comment]
Thanks, @fsteeg. It's ready for review now. Will you review or should I assign somebody else?

**Comment by acka47** [comment]
> - [ ] Add several missing SkoHub blog posts (last one is from July 2021)
> 
> Re. the last point: @sroertgen it probably makes sense to open a separate issue for this and maybe even write a script to create the JSON files automatically?

I will open another issue for this.

**Comment by fsteeg** [comment]
> Will you review or should I assign somebody else? However, it would be great if you could add some reasonable end dates to the fix and playground projects.

Yes, I'll review and add dates, then reassign to you for final review.

**Review by fsteeg — APPROVED** [review]
Looks good to me :+1:

Added start and end dates in https://github.com/hbz/lobid/pull/524/commits/b0adcacbd5090e55886adb300ae99e86edf2a154

Deployed to test: http://stage.lobid.org/team-de/

**Comment by acka47** [comment]
+1 Please deploy (I noticed that past projects are not listed on a person profile page. Thus might be something to add in the future.)

**Comment by fsteeg** [comment]
> I noticed that past projects are not listed on a person profile page.

Now showing former projects on member pages:

http://stage.lobid.org/team/ap

**Pull request merged**
