### PR TITLE
Add discourse

### PR DESCRIPTION
**Pull request by sroertgen**
https://github.com/hbz/lobid/issues/526

Removed twitter links
Added Discourse links

### CODE REVIEW

**Review by fsteeg — APPROVED** [review]
Looks good to me (diff is a bit hard to read due to formatting/indentation changes).

Deployed to stage for review: http://stage.lobid.org/team/

**Comment by dr0i** [comment]
ping @acka47 to throw an eye

**Review by acka47 — CHANGES_REQUESTED** [review]
Hmm, although this team site runs on the lobid.org domain, it encompasses all our projects and services. And there are categories for several services on metadaten.community:lobid, SkoHub, Metafactue, OERSI. So it would probably make more sense to add the discourse links to the service descriptions, wouldn't it?

**Comment by sroertgen** [comment]
We decided to remove the discourse link for now and the link to the mailing list.

**Comment by sroertgen** [comment]
Added changes as requested.
@fsteeg Please deploy to stage for review

**Comment by fsteeg** [comment]
Deployed to stage for review: http://stage.lobid.org/team/

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
