### PR TITLE
Switch from twitter to mastodon

### PR DESCRIPTION
**Pull request by dr0i**
See #483 .

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to http://stage.lobid.org/ @acka47 you can do functional review.

**Comment by acka47** [comment]
At `/organisations` and `/resources` I still see the Twitter logo/link.

**Comment by dr0i** [comment]
You mean e.g. http://stage.lobid.org/organisations ? That's done in their respective repos.

**Review by acka47 — APPROVED** [review]
+1

**Comment by dr0i** [comment]
Assigning @sroertgen for code review.

**Review by sroertgen — APPROVED** [review]
LGTM

**Pull request merged**
