### PR TITLE
Use working image URL in Adrian's profile

### PR DESCRIPTION
**Pull request by acka47**
I updated the URL in the JSON. Should I also have updated it in the HTML? I guess it will be generated automatically so I left it.

https://github.com/hbz/lobid/blob/c888a5be5e3af84b8457b141c61242128bba3b7d/team/ap#L100

### CODE REVIEW

**Comment by fsteeg** [comment]
As discussed offline, you need to update the HTML as well, since after the removal of the old Play app, these are just static files.

**Comment by acka47** [comment]
I had to update it in three places: JSON file, HTML image link, embedded JSON-LD in HTML. This is not convenient at all...

**Comment by fsteeg** [comment]
> I had to update it in three places: JSON file, HTML image link, embedded JSON-LD in HTML. This is not convenient at all...

Yup, it isn't. I am even more bothered about the lack of an English version. Maybe we should switch back to a web app here instead of static sites? Or some static site generator like Gatsby?

**Comment by acka47** [comment]
What is with the pending check?

**Comment by fsteeg** [comment]
> What is it with the pending check?

Weird, no idea. I've disabled the Travis webhook for this repo. Maybe that's something really old?

@dr0i Could you deploy this? I'm not sure how/where to deploy (these are static sites in Apache now, correct?)

**Comment by dr0i** [comment]
If you also like, as I assume, to use the new picture also in the [team's page](http://lobid.org/team/) , I will change the index.html not only at the server but also in git. Just hit me.

**Comment by dr0i** [comment]
@fsteeg correct, this repo is checked out at emphytos:/srv/www/htdocs/lobid.org/ .

**Comment by dr0i** [comment]
@acka47 I updated also the branch. Please have a look.

**Comment by dr0i** [comment]
Merged and deployed. Closed.

**Pull request merged**
