### PR TITLE
Correct HTML validation errors, adjust CSS

### PR DESCRIPTION
**Pull request by Phu2**
See #497.

### CODE REVIEW

**Review by dr0i — APPROVED** [review]
code looks good. However I don't know how rendered looks ("functional review"). Can you provide that? See https://github.com/hbz/lobid/tree/master/gatsby/lobid for how to. Seems a css issue when trying to resolve http://stage.lobid.org/ (note: https is not activated).

**Comment by Phu2** [comment]
Trying to build but getting an Graphql error: https://github.com/hbz/lobid/issues/500

**Comment by Phu2** [comment]
Deployed on http://stage.lobid.org/ for functional review
See also https://validator.w3.org/nu/?doc=http%3A%2F%2Fstage.lobid.org%2F

**Review by dr0i — APPROVED** [review]
great - thx!

**Pull request merged**
