### PR TITLE
Add Anna, Infrastrukturinitiativew Metadaten and slides for SkoHub workshops

### PR DESCRIPTION
**Pull request by acka47**

### CODE REVIEW

**Comment by fsteeg** [comment]
Pushed some tweaks in https://github.com/hbz/lobid/pull/484/commits/957fdc6c8aa4be1f816bab5f7578d8f8a05f7fb3 (e.g. removed `endDate`, currently projects with an `endDate` are displayed under former projects and not shown on the team member pages).

Deployed to stage:

http://stage.lobid.org/team
http://stage.lobid.org/team/ak

@kaena83 Let me know it you want an image (URL or file).

**Comment by kaena83** [comment]
@fsteeg Thanks for adding me :) Here's the pic:
AnnaKeller_Porträt

**Comment by acka47** [comment]
I have added the picture with [883f20e](https://github.com/hbz/lobid/pull/484/commits/883f20e27b20040c7ce61753c4243c83a4ba1dc9). 

I have also reviewd the changes on staging and noticed the following.

- The link label for the new project isn't ideal. How can I change it?
image
- Anoter question: How do I add line breaks to the description text at http://stage.lobid.org/project/infrastrukturinitiative I guess by just adding `\n`, right?

**Comment by fsteeg** [comment]
> The link label for the new project isn't ideal. How can I change it?

If you add an `alternateName` it will be used there.

> Anoter question: How do I add line breaks to the description text at http://stage.lobid.org/project/infrastrukturinitiative I guess by just adding \n, right?

No, since in HTML that line break has no effect. Currently, there is no way to add styling, the texts have been shorter so far. HTML tags are currently escaped, but I think that would be the way to implement styling, if we want that.

**Comment by fsteeg** [comment]
Added label as discussed with @acka47 in chat, deployed to production, closing:

http://lobid.org/team
http://lobid.org/team/ak

**Pull request merged**
